# Generated by Django 3.2.4 on 2021-06-19 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.FileField(null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('birth_date', models.DateField(default='2021-06-19')),
                ('photos', models.ManyToManyField(blank=True, to='api.PhotoModel')),
            ],
        ),
    ]
