# Generated by Django 3.2.3 on 2021-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('type', models.CharField(max_length=60)),
                ('photos', models.CharField(max_length=60)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
