# Generated by Django 3.2.4 on 2021-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210608_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='pet',
        ),
        migrations.AddField(
            model_name='petmodel',
            name='photos',
            field=models.ManyToManyField(blank=True, to='api.PhotoModel'),
        ),
    ]
