# Generated by Django 3.2.4 on 2021-06-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210608_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='url',
        ),
    ]
