# Generated by Django 3.2.4 on 2021-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_photomodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
